# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.haskell]
command = "ormolu"
includes = ["*.hs"]
options = [
  "--mode", "check",
  "--check-idempotence",
]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]
excludes = [
  "nix/packages/*.nix",
  "nix/sources.nix",
]
options = [
  "--check",
]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = [
    "--indent", "2",
    "--simplify",
    "--diff",
]

[formatter.prettier]
command = "prettier"
includes = [
    "*.json",
    "*.md",
    "*.yaml",
]
options = [
  "--list-different"
]
excludes = [
  "nix/sources.json",
]
